const dataIdioms = [
 // --- 成語故事類 ---
  { "id": "i1", "type": "成語故事", "title": "完璧歸趙", "icon": "💎", "era": "戰國時期", "year": -283, "location": "河北邯鄲", "coords": [36.6, 114.5], "regions": ["河北", "陝西"], "content": "秦昭王想用城池換取和氏璧，藺相如奉命帶璧出使，憑藉機智勇敢，最終將和氏璧完好歸還趙國。", "evidence": "《史記·廉頗藺相如列傳》。比喻把原物完好地歸還本人。", "link": "https://zh.wiktionary.org/zh-hant/%E5%AE%8C%E7%92%A7%E6%AD%B8%E8%B6%99" },
  { "id": "i2", "type": "成語故事", "title": "破釜沉舟", "icon": "💥", "era": "秦末漢初", "year": -207, "location": "河北巨鹿", "coords": [37.22, 115.03], "regions": ["河北"], "content": "項羽渡河救援巨鹿後，下令砸碎鍋具、鑿沉船隻，只帶三天乾糧，以示必死決心，最終大破秦軍。", "evidence": "《史記·項羽本紀》。比喻下定必死的決心，不留退路。", "link": "https://zh.wikipedia.org/zh-tw/%E7%A0%B4%E9%87%9C%E6%B2%89%E8%88%9F" },
  { "id": "i3", "type": "成語故事", "title": "草木皆兵", "icon": "🍃", "era": "東晉", "year": 383, "location": "安徽壽縣 (淝水)", "coords": [32.58, 116.78], "regions": ["安徽"], "content": "淝水之戰中，前秦皇帝苻堅見東晉軍隊陣容嚴整，把八公山上的草木都當成了晉軍，心中十分恐懼。", "evidence": "《晉書·苻堅載記》。形容人在驚慌時疑神疑鬼。", "link": "https://zh.wiktionary.org/zh-hant/%E8%8D%89%E6%9C%A8%E7%9A%86%E5%85%B5" },
  { "id": "i4", "type": "成語故事", "title": "揠苗助長", "icon": "🌱", "era": "春秋戰國", "year": -400, "location": "河南商丘 (宋國)", "coords": [34.4, 115.6], "regions": ["河南"], "content": "宋國有個人嫌禾苗長得太慢，就把禾苗一棵棵往上拔高，結果禾苗反而全都枯死了。", "evidence": "《孟子·公孫丑上》。比喻違反規律急於求成，反而把事情弄糟。", "link": "https://zh.wiktionary.org/zh-hant/%E6%8F%A0%E8%8B%97%E5%8A%A9%E9%95%B7" },
  { "id": "i5", "type": "成語故事", "title": "守株待兔", "icon": "🐇", "era": "春秋戰國", "year": -350, "location": "河南商丘 (宋國)", "coords": [34.3, 115.7], "regions": ["河南"], "content": "宋國農夫偶然撿到一隻撞死在樹樁上的兔子，從此放下農具，天天守在樹樁旁希望能再撿到兔子。", "evidence": "《韓非子·五蠹》。比喻拘泥守成，不知變通，或妄想不勞而獲。", "link": "https://zh.wiktionary.org/zh-hant/%E5%AE%88%E6%A0%AA%E5%BE%85%E5%85%94" },
  { "id": "i6", "type": "成語故事", "title": "刻舟求劍", "icon": "🗡️", "era": "戰國時期", "year": -300, "location": "湖北荊州 (楚國)", "coords": [30.3, 112.2], "regions": ["湖北"], "content": "楚國人渡江時劍掉入水中，他在船身刻下記號，等船靠岸後才從記號處下水找劍。", "evidence": "《呂氏春秋·察今》。比喻辦事刻板，不知道因時制宜。", "link": "https://zh.wiktionary.org/zh-hant/%E5%88%BB%E8%88%9F%E6%B1%82%E5%8A%8D" },
  { "id": "i7", "type": "成語故事", "title": "掩耳盜鈴", "icon": "🔔", "era": "春秋時期", "year": -450, "location": "山西太原 (晉國)", "coords": [37.8, 112.5], "regions": ["山西"], "content": "有人偷了一口大鐘，想把它敲碎帶走，怕鐘聲引來別人，就捂住自己的耳朵去砸。", "evidence": "《呂氏春秋·自知》。比喻自欺欺人。", "link": "https://zh.wiktionary.org/zh-hant/%E6%8E%A9%E8%80%B3%E7%9B%9C%E9%88%B4" },
  { "id": "i8", "type": "成語故事", "title": "指鹿為馬", "icon": "🦌", "era": "秦朝", "year": -207, "location": "陝西咸陽", "coords": [34.3, 108.7], "regions": ["陝西"], "content": "權臣趙高為了測試群臣是否順從他，牽了一隻鹿獻給秦二世，卻硬說是一匹馬。", "evidence": "《史記·秦始皇本紀》。比喻顛倒是非，混淆黑白。", "link": "https://zh.wiktionary.org/zh-hant/%E6%8C%87%E9%B9%BF%E7%82%BA%E9%A6%AC" },
  { "id": "i9", "type": "成語故事", "title": "臥薪嘗膽", "icon": "🪵", "era": "春秋時期", "year": -494, "location": "浙江紹興 (越國)", "coords": [30.0, 120.5], "regions": ["浙江", "江蘇"], "content": "越王勾踐戰敗後，睡在柴草上，每天嚐一口苦膽，不忘復國之恥，最終消滅了吳國。", "evidence": "《史記·越王勾踐世家》。比喻刻苦自勵，發憤圖強。", "link": "https://zh.wiktionary.org/zh-hant/%E8%87%A5%E8%96%AA%E5%98%97%E8%86%BD" },
  { "id": "i10", "type": "成語故事", "title": "三顧茅廬", "icon": "🛖", "era": "東漢末年", "year": 207, "location": "湖北襄陽 (隆中)", "coords": [32.0, 112.1], "regions": ["湖北"], "content": "劉備為了求得諸葛亮出山輔佐，三次親自到南陽隆中的草廬去拜訪他。", "evidence": "《三國志·諸葛亮傳》。比喻誠心誠意地邀請人家。", "link": "https://zh.wiktionary.org/zh-hant/%E4%B8%89%E9%A1%A7%E8%8C%85%E5%BB%AC" },
  { "id": "i11", "type": "成語故事", "title": "聞雞起舞", "icon": "🐓", "era": "東晉", "year": 313, "location": "河北保定", "coords": [38.8, 115.5], "regions": ["河北"], "content": "祖逖與好友劉琨為了報效國家，半夜聽到雞叫聲就起床拔劍練武。", "evidence": "《晉書·祖逖傳》。比喻有志之士奮發圖強。", "link": "https://zh.wiktionary.org/zh-hant/%E8%81%9E%E9%9B%9E%E8%B5%B7%E8%88%9E" },
  { "id": "i12", "type": "成語故事", "title": "望梅止渴", "icon": "🍒", "era": "東漢末年", "year": 198, "location": "河南許昌", "coords": [34.0, 113.8], "regions": ["河南", "安徽"], "content": "曹操率軍行軍途中缺水，便騙士兵前面有一大片梅林，士兵聽了流出口水，便暫時解了渴。", "evidence": "《世說新語·假譎》。比喻用空想來安慰自己。", "link": "https://zh.wiktionary.org/zh-hant/%E6%9C%9B%E6%A2%85%E6%AD%A2%E6%B8%B4" },
  { "id": "i13", "type": "成語故事", "title": "狐假虎威", "icon": "🦊", "era": "戰國時期", "year": -330, "location": "湖北一帶 (楚國)", "coords": [30.5, 114.3], "regions": ["湖北", "湖南"], "content": "老虎抓住狐狸，狐狸謊稱自己是百獸之王，讓老虎跟在後面走，野獸看到老虎都嚇跑了，老虎以為是怕狐狸。", "evidence": "《戰國策·楚策一》。比喻藉著有權勢者的威風來欺壓別人。", "link": "https://zh.wiktionary.org/zh-hant/%E7%8B%90%E5%81%87%E8%99%8E%E5%A8%81" },
  { "id": "i14", "type": "成語故事", "title": "井底之蛙", "icon": "🐸", "era": "戰國時期", "year": -300, "location": "黃河流域", "coords": [34.8, 114.0], "regions": ["山東", "河南"], "content": "井裡的青蛙以為天只有井口那麼大，對來自東海的海鱉誇耀生活，卻不知外面的世界有多寬廣。", "evidence": "《莊子·秋水》。比喻見識短淺的人。", "link": "https://zh.wiktionary.org/zh-hant/%E4%BA%95%E5%BA%95%E4%B9%8B%E8%9B%99" },
 ];