const dataMyths = [
  // --- 神話、童話類 ---
  { "id": "m1", "type": "神話、童話", "title": "盤古開天", "icon": "⛰️", "era": "神話時代", "year": -3000, "location": "中原 / 崑崙山脈", "coords": [35.5, 85.5], "regions": ["中國", "台灣"], "content": "天地渾沌如雞子，盤古生在其中。死後身軀化為三山五嶽、江河星辰。", "evidence": "故事背景為宇宙初開。最早文字記載於三國時代徐整的《三五歷紀》。", "link": "https://zh.wikipedia.org/zh-tw/%E7%9B%A4%E5%8F%A4" },
  { "id": "m2", "type": "神話、童話", "title": "女媧造人與補天", "icon": "🏺", "era": "神話時代", "year": -2800, "location": "甘肅天水 / 中原", "coords": [34.58, 105.73], "regions": ["甘肅", "陝西", "河南"], "content": "女媧摶黃土造人。後因共工撞斷不周山，女媧煉五色石補天。", "evidence": "屬上古神話。甘肅天水一帶有大量伏羲與女媧的早期祭祀遺址。", "link": "https://zh.wikipedia.org/zh-tw/%E5%A5%B3%E5%A8%B2" },
  { "id": "m7", "type": "神話、童話", "title": "黃帝戰蚩尤", "icon": "⚔️", "era": "五帝時期", "year": -2700, "location": "河北涿鹿", "coords": [40.38, 115.18], "regions": ["河北", "北京", "山西"], "content": "黃帝聯合炎帝，在應龍與女魃協助下，於涿鹿擊敗蚩尤。", "evidence": "故事發生於約西元前27世紀。現今河北張家口市涿鹿縣仍有黃帝城遺址。", "link": "https://zh.wikipedia.org/wiki/%E6%B6%BF%E9%B9%BF%E4%B9%8B%E6%88%B0" },
  { "id": "m8", "type": "神話、童話", "title": "夸父追日", "icon": "🏃", "era": "神話時代", "year": -2600, "location": "黃河流域", "coords": [34.5, 110.0], "regions": ["河南", "山西", "陝西"], "content": "夸父為了抓住太陽，一路追趕到大澤，最終渴死，其手杖化為鄧林（桃林）。", "evidence": "《山海經·海外北經》。象徵古代先民探索自然與抗爭的精神。", "link": "https://zh.wikipedia.org/zh-tw/%E5%A4%B8%E7%88%B6" },
  { "id": "m9", "type": "神話、童話", "title": "精衛填海", "icon": "🐦", "era": "神話時代", "year": -2650, "location": "山西發鳩山 / 東海", "coords": [36.0, 113.0], "regions": ["山西", "山東"], "content": "炎帝之女女娃在東海溺水而亡，化作精衛鳥，每天銜樹枝與石塊想要填平東海。", "evidence": "《山海經·北山經》。常被用來比喻意志堅決，不畏艱難。", "link": "https://zh.wikipedia.org/zh-tw/%E7%B2%BE%E8%A1%9B%E5%A1%AB%E6%B5%B7" },
  { "id": "m10", "type": "神話、童話", "title": "后羿射日", "icon": "🏹", "era": "神話時代", "year": -2400, "location": "山西屯留 (相傳)", "coords": [36.1, 112.8], "regions": ["山西", "河南", "山東"], "content": "天上同時出現十個太陽，烤焦了大地，后羿拉開神弓，射下了九個太陽，拯救了蒼生。", "evidence": "神話無精確座標，但後世多將山西長子、屯留一帶的山脈視為后羿活躍地。", "link": "https://zh.wikipedia.org/zh-tw/%E5%90%8E%E7%BE%BF" },
  { "id": "m11", "type": "神話、童話", "title": "神農嘗百草", "icon": "🌿", "era": "神話時代", "year": -2850, "location": "湖北神農架", "coords": [31.7, 110.6], "regions": ["湖北", "陝西"], "content": "炎帝神農氏為了解除百姓的病痛，親自品嚐百草，分辨藥性，最終教導人民醫藥與農耕。", "evidence": "《淮南子·修務訓》。湖北神農架相傳是神農氏採藥的地方。", "link": "https://zh.wikipedia.org/zh-tw/%E7%A5%9E%E8%BE%B2" },
  { "id": "m12", "type": "神話、童話", "title": "大禹治水", "icon": "🌊", "era": "夏朝建立", "year": -2070, "location": "河南嵩山", "coords": [34.5, 113.0], "regions": ["河南", "山西", "安徽", "浙江"], "content": "大禹改「堵」為「疏」，歷時十三年平息水患，三過家門而不入。", "evidence": "記載於《尚書·禹貢》。現代考古於二里頭遺址發現大規模防洪遺跡。", "link": "https://zh.wikipedia.org/wiki/%E5%A4%A7%E7%A6%B9%E6%B2%BB%E6%B0%B4" },
  { "id": "m13", "type": "神話、童話", "title": "西遊記 (唐僧取經)", "icon": "🐒", "era": "唐朝", "year": 627, "location": "陝西長安出發", "coords": [34.26, 108.93], "regions": ["陝西", "甘肅", "青海", "新疆"], "content": "孫悟空大鬧天宮後被壓五指山，後於長安跟隨唐僧前往西天取經。", "evidence": "小說《西遊記》成書於明代，歷史時間為唐太宗貞觀年間。", "link": "https://zh.wikipedia.org/wiki/%E8%A5%BF%E6%B8%B8%E8%AE%B0" },
  { "id": "m14", "type": "神話、童話", "title": "白蛇傳", "icon": "🐍", "era": "南宋", "year": 1127, "location": "浙江杭州西湖", "coords": [30.25, 120.15], "regions": ["浙江", "江蘇"], "content": "白素貞與許仙在西湖斷橋相遇，後被法海鎮壓於雷峰塔下。", "evidence": "故事背景設定在南宋時期的臨安 (今杭州)。", "link": "https://zh.wikipedia.org/zh-tw/%E7%99%BD%E8%9B%87%E4%BC%A0" },
  { "id": "t1", "type": "神話、童話", "title": "邵族逐白鹿", "icon": "🦌", "era": "神話時代", "year": -1000, "location": "台灣南投 (日月潭)", "coords": [23.86, 120.91], "regions": ["台灣"], "content": "邵族先民為了追逐一隻罕見的白鹿，翻山越嶺來到了美麗的日月潭，從此定居於此。", "evidence": "台灣原住民邵族的創世傳說，解釋了部落遷徙的歷史。", "link": "https://zh.wikipedia.org/zh-tw/%E9%82%B5%E6%97%8F" },
  { "id": "t2", "type": "神話、童話", "title": "泰雅族射日", "icon": "🏹", "era": "神話時代", "year": -1500, "location": "台灣中央山脈", "coords": [24.0, 121.0], "regions": ["台灣"], "content": "遠古有兩個太陽輪流照射大地，泰雅族勇士父子接力前往世界盡頭，最終射下一個太陽，變成了月亮。", "evidence": "泛泰雅族系廣泛流傳的射日神話。", "link": "https://zh.wikipedia.org/wiki/%E6%B3%B0%E9%9B%85%E6%97%8F" },
  { "id": "j1", "type": "神話、童話", "title": "天岩戶傳說", "icon": "☀️", "era": "神話時代", "year": -600, "location": "日本九州 (宮崎縣)", "coords": [32.7, 131.3], "regions": ["日本"], "content": "太陽女神天照大神因憤怒躲入天岩戶中，讓世界陷入黑暗。眾神在洞外跳起熱鬧的祭祀舞，才成功將她引出。", "evidence": "出自日本最古老的史書《古事記》與《日本書紀》。", "link": "https://zh.wikipedia.org/zh-tw/%E5%A4%A9%E5%B2%A9%E6%88%B6" },
  { "id": "j2", "type": "神話、童話", "title": "桃太郎", "icon": "🍑", "era": "室町時代", "year": 1300, "location": "日本岡山", "coords": [34.6, 133.9], "regions": ["日本"], "content": "從巨大的桃子中誕生的桃太郎，帶著老爺爺老奶奶給的糯米糰子，與小白狗、小猴子、雉雞一同前往鬼島討伐惡鬼。", "evidence": "日本最著名的民間童話之一，岡山縣被普遍視為故事發源地。", "link": "https://zh.wikipedia.org/wiki/%E6%A1%83%E5%A4%AA%E9%83%8E" },
  { "id": "k1", "type": "神話、童話", "title": "檀君建國", "icon": "🐻", "era": "上古時代", "year": -2333, "location": "朝鮮半島", "coords": [39.0, 126.0], "regions": ["韓國"], "content": "天神之子桓雄下凡，一隻熊在洞窟中只吃艾草與大蒜撐過了考驗化為女人，與桓雄生下檀君，建立了古朝鮮。", "evidence": "《三國遺事》。檀君被視為韓民族的始祖。", "link": "https://zh.wikipedia.org/wiki/%E6%AA%80%E5%90%9B" },
  { "id": "r1", "type": "神話、童話", "title": "芭芭雅嘎", "icon": "🧙‍♀️", "era": "中世紀", "year": 1200, "location": "俄羅斯西伯利亞", "coords": [60.0, 90.0], "regions": ["俄羅斯"], "content": "住在森林深處、長著雞腳的木屋裡的強大女巫。她坐著研缽在空中飛行，有時會吃人，有時又會指引迷路的勇士。", "evidence": "斯拉夫民間傳說中最著名的女巫形象。", "link": "https://zh.wikipedia.org/wiki/%E8%8A%AD%E5%B7%B4%E9%9B%85%E5%98%8E" },
  { "id": "r2", "type": "神話、童話", "title": "火鳥", "icon": "🔥", "era": "中世紀", "year": 1000, "location": "俄羅斯西部", "coords": [56.0, 38.0], "regions": ["俄羅斯"], "content": "伊凡王子為了尋找偷吃金蘋果的火鳥，在神奇怪狼的幫助下經歷重重考驗，最終抱得美人歸並帶回火鳥。", "evidence": "俄羅斯著名童話《伊凡王子、火鳥與灰狼》。", "link": "https://zh.wikipedia.org/wiki/%E7%81%AB%E9%B8%9F" },

];