const mythsData = [
  // --- 神話、童話類 ---
  { "id": "m1", "type": "神話、童話", "title": "盤古開天", "icon": "⛰️", "era": "神話時代", "year": -3000, "location": "中原 / 崑崙山脈", "coords": [35.5, 85.5], "regions": ["中國", "台灣"], "content": "天地渾沌如雞子，盤古生在其中。死後身軀化為三山五嶽、江河星辰。", "evidence": "故事背景為宇宙初開。最早文字記載於三國時代徐整的《三五歷紀》。", "link": "https://zh.wikipedia.org/zh-tw/%E7%9B%A4%E5%8F%A4" },
  { "id": "m2", "type": "神話、童話", "title": "女媧造人與補天", "icon": "🏺", "era": "神話時代", "year": -2800, "location": "甘肅天水 / 中原", "coords": [34.58, 105.73], "regions": ["甘肅", "陝西", "河南"], "content": "女媧摶黃土造人。後因共工撞斷不周山，女媧煉五色石補天。", "evidence": "屬上古神話。甘肅天水一帶有大量伏羲與女媧的早期祭祀遺址。", "link": "https://zh.wikipedia.org/zh-tw/%E5%A5%B3%E5%A8%B2" },
  { "id": "m7", "type": "神話、童話", "title": "黃帝戰蚩尤", "icon": "⚔️", "era": "五帝時期", "year": -2700, "location": "河北涿鹿", "coords": [40.38, 115.18], "regions": ["河北", "北京", "山西"], "content": "黃帝聯合炎帝，在應龍與女魃協助下，於涿鹿擊敗蚩尤。", "evidence": "故事發生於約西元前27世紀。現今河北張家口市涿鹿縣仍有黃帝城遺址。", "link": "https://zh.wikipedia.org/wiki/%E6%B6%BF%E9%B9%BF%E4%B9%8B%E6%88%B0" },
  { "id": "m8", "type": "神話、童話", "title": "夸父追日", "icon": "🏃", "era": "神話時代", "year": -2600, "location": "黃河流域", "coords": [34.5, 110.0], "regions": ["河南", "山西", "陝西"], "content": "夸父為了抓住太陽，一路追趕到大澤，最終渴死，其手杖化為鄧林（桃林）。", "evidence": "《山海經·海外北經》。象徵古代先民探索自然與抗爭的精神。", "link": "https://zh.wikipedia.org/zh-tw/%E5%A4%B8%E7%88%B6" },
  { "id": "m9", "type": "神話、童話", "title": "精衛填海", "icon": "🐦", "era": "神話時代", "year": -2650, "location": "山西發鳩山 / 東海", "coords": [36.0, 113.0], "regions": ["山西", "山東"], "content": "炎帝之女女娃在東海溺水而亡，化作精衛鳥，每天銜樹枝與石塊想要填平東海。", "evidence": "《山海經·北山經》。常被用來比喻意志堅決，不畏艱難。", "link": "https://zh.wikipedia.org/zh-tw/%E7%B2%BE%E8%A1%9B%E5%A1%AB%E6%B5%B7" },
  { "id": "m10", "type": "神話、童話", "title": "后羿射日", "icon": "🏹", "era": "神話時代", "year": -2400, "location": "山西屯留 (相傳)", "coords": [36.1, 112.8], "regions": ["山西", "河南", "山東"], "content": "天上同時出現十個太陽，烤焦了大地，后羿拉開神弓，射下了九個太陽，拯救了蒼生。", "evidence": "神話無精確座標，但後世多將山西長子、屯留一帶的山脈視為后羿活躍地。", "link": "https://zh.wikipedia.org/zh-tw/%E5%90%8E%E7%BE%BF" },
  { "id": "m11", "type": "神話、童話", "title": "神農嘗百草", "icon": "🌿", "era": "神話時代", "year": -2850, "location": "湖北神農架", "coords": [31.7, 110.6], "regions": ["湖北", "陝西"], "content": "炎帝神農氏為了解除百姓的病痛，親自品嚐百草，分辨藥性，最終教導人民醫藥與農耕。", "evidence": "《淮南子·修務訓》。湖北神農架相傳是神農氏採藥的地方。", "link": "https://zh.wikipedia.org/zh-tw/%E7%A5%9E%E8%BE%B2" },
  { "id": "m12", "type": "神話、童話", "title": "大禹治水", "icon": "🌊", "era": "夏朝建立", "year": -2070, "location": "河南嵩山", "coords": [34.5, 113.0], "regions": ["河南", "山西", "安徽", "浙江"], "content": "大禹改「堵」為「疏」，歷時十三年平息水患，三過家門而不入。", "evidence": "記載於《尚書·禹貢》。現代考古於二里頭遺址發現大規模防洪遺跡。", "link": "https://zh.wikipedia.org/wiki/%E5%A4%A7%E7%A6%B9%E6%B2%BB%E6%B0%B4" },
  { "id": "m13", "type": "神話、童話", "title": "西遊記 (唐僧取經)", "icon": "🐒", "era": "唐朝", "year": 627, "location": "陝西長安出發", "coords": [34.26, 108.93], "regions": ["陝西", "甘肅", "青海", "新疆"], "content": "孫悟空大鬧天宮後被壓五指山，後於長安跟隨唐僧前往西天取經。", "evidence": "小說《西遊記》成書於明代，歷史時間為唐太宗貞觀年間。", "link": "https://zh.wikipedia.org/wiki/%E8%A5%BF%E6%B8%B8%E8%AE%B0" },
  { "id": "m14", "type": "神話、童話", "title": "白蛇傳", "icon": "🐍", "era": "南宋", "year": 1127, "location": "浙江杭州西湖", "coords": [30.25, 120.15], "regions": ["浙江", "江蘇"], "content": "白素貞與許仙在西湖斷橋相遇，後被法海鎮壓於雷峰塔下。", "evidence": "故事背景設定在南宋時期的臨安 (今杭州)。", "link": "https://zh.wikipedia.org/zh-tw/%E7%99%BD%E8%9B%87%E4%BC%A0" },

  // --- 全球神話與童話擴充 ---
  { "id": "t1", "type": "神話、童話", "title": "邵族逐白鹿", "icon": "🦌", "era": "神話時代", "year": -1000, "location": "台灣南投 (日月潭)", "coords": [23.86, 120.91], "regions": ["台灣"], "content": "邵族先民為了追逐一隻罕見的白鹿，翻山越嶺來到了美麗的日月潭，從此定居於此。", "evidence": "台灣原住民邵族的創世傳說，解釋了部落遷徙的歷史。", "link": "https://zh.wikipedia.org/zh-tw/%E9%82%B5%E6%97%8F" },
  { "id": "t2", "type": "神話、童話", "title": "泰雅族射日", "icon": "🏹", "era": "神話時代", "year": -1500, "location": "台灣中央山脈", "coords": [24.0, 121.0], "regions": ["台灣"], "content": "遠古有兩個太陽輪流照射大地，泰雅族勇士父子接力前往世界盡頭，最終射下一個太陽，變成了月亮。", "evidence": "泛泰雅族系廣泛流傳的射日神話。", "link": "https://zh.wikipedia.org/wiki/%E6%B3%B0%E9%9B%85%E6%97%8F" },
  { "id": "j1", "type": "神話、童話", "title": "天岩戶傳說", "icon": "☀️", "era": "神話時代", "year": -600, "location": "日本九州 (宮崎縣)", "coords": [32.7, 131.3], "regions": ["日本"], "content": "太陽女神天照大神因憤怒躲入天岩戶中，讓世界陷入黑暗。眾神在洞外跳起熱鬧的祭祀舞，才成功將她引出。", "evidence": "出自日本最古老的史書《古事記》與《日本書紀》。", "link": "https://zh.wikipedia.org/zh-tw/%E5%A4%A9%E5%B2%A9%E6%88%B6" },
  { "id": "j2", "type": "神話、童話", "title": "桃太郎", "icon": "🍑", "era": "室町時代", "year": 1300, "location": "日本岡山", "coords": [34.6, 133.9], "regions": ["日本"], "content": "從巨大的桃子中誕生的桃太郎，帶著老爺爺老奶奶給的糯米糰子，與小白狗、小猴子、雉雞一同前往鬼島討伐惡鬼。", "evidence": "日本最著名的民間童話之一，岡山縣被普遍視為故事發源地。", "link": "https://zh.wikipedia.org/wiki/%E6%A1%83%E5%A4%AA%E9%83%8E" },
  { "id": "k1", "type": "神話、童話", "title": "檀君建國", "icon": "🐻", "era": "上古時代", "year": -2333, "location": "朝鮮半島", "coords": [39.0, 126.0], "regions": ["韓國"], "content": "天神之子桓雄下凡，一隻熊在洞窟中只吃艾草與大蒜撐過了考驗化為女人，與桓雄生下檀君，建立了古朝鮮。", "evidence": "《三國遺事》。檀君被視為韓民族的始祖。", "link": "https://zh.wikipedia.org/wiki/%E6%AA%80%E5%90%9B" },
  { "id": "r1", "type": "神話、童話", "title": "芭芭雅嘎", "icon": "🧙‍♀️", "era": "中世紀", "year": 1200, "location": "俄羅斯西伯利亞", "coords": [60.0, 90.0], "regions": ["俄羅斯"], "content": "住在森林深處、長著雞腳的木屋裡的強大女巫。她坐著研缽在空中飛行，有時會吃人，有時又會指引迷路的勇士。", "evidence": "斯拉夫民間傳說中最著名的女巫形象。", "link": "https://zh.wikipedia.org/wiki/%E8%8A%AD%E5%B7%B4%E9%9B%85%E5%98%8E" },
  { "id": "r2", "type": "神話、童話", "title": "火鳥", "icon": "🔥", "era": "中世紀", "year": 1000, "location": "俄羅斯西部", "coords": [56.0, 38.0], "regions": ["俄羅斯"], "content": "伊凡王子為了尋找偷吃金蘋果的火鳥，在神奇怪狼的幫助下經歷重重考驗，最終抱得美人歸並帶回火鳥。", "evidence": "俄羅斯著名童話《伊凡王子、火鳥與灰狼》。", "link": "https://zh.wikipedia.org/wiki/%E7%81%AB%E9%B8%9F" },

  // --- 節日起源類 ---
  { "id": "h1", "type": "節日起源", "title": "春節 (年獸傳說)", "icon": "🧨", "era": "上古時代", "year": -2000, "location": "中原地區", "coords": [34.26, 108.90], "regions": ["中國", "台灣"], "content": "相傳古時有怪獸名「年」，每逢除夕便出來傷人。後來人們發現「年」怕紅、怕光、怕巨響，於是有了貼春聯、放鞭炮的習俗。", "evidence": "春節源於殷商時期的歲首祭祀，年獸傳說則是後世民間故事。", "link": "https://zh.wikipedia.org/zh-tw/%E6%98%A5%E8%8A%82" },
  { "id": "h2", "type": "節日起源", "title": "元宵節 (東方朔與元宵)", "icon": "🏮", "era": "西漢", "year": -104, "location": "陝西長安", "coords": [34.40, 109.80], "regions": ["陝西"], "content": "傳說漢武帝時，東方朔為了幫宮女「元宵」與家人團聚，假傳火神要燒長安，讓全城掛滿紅燈籠並做湯圓，成功瞞過玉帝。", "evidence": "元宵節賞燈習俗始於漢明帝時期，此為民間流傳的節日傳說。", "link": "https://zh.wikipedia.org/zh-tw/%E5%85%83%E5%AE%B5%E8%8A%82" },
  { "id": "h3", "type": "節日起源", "title": "清明節 (介子推)", "icon": "🌱", "era": "春秋時期", "year": -636, "location": "山西綿山", "coords": [36.80, 111.90], "regions": ["山西"], "content": "晉文公重耳為了逼功臣介子推下山為官而放火燒山，不料將其燒死。為了紀念他，下令當日禁火寒食，後演變為清明節。", "evidence": "清明節融合了古代的「寒食節」習俗，《左傳》記載了介子推不言祿的真實歷史。", "link": "https://zh.wikipedia.org/zh-tw/%E6%B8%85%E6%98%8E" },
  { "id": "h4", "type": "節日起源", "title": "端午節 (屈原投江)", "icon": "🛶", "era": "戰國時期", "year": -278, "location": "湖南汨羅江", "coords": [28.80, 113.00], "regions": ["湖南", "湖北", "台灣"], "content": "楚國遭秦軍攻破，屈原悲憤抱石投江殉國。百姓划船驅趕魚群、投下飯糰，演變為賽龍舟與吃粽子。", "evidence": "《史記·屈原賈生列傳》。端午原本是驅瘟避疫的節日，後與屈原事蹟結合。", "link": "https://zh.wikipedia.org/zh-tw/%E7%AB%AF%E5%8D%88%E8%8A%82" },
  { "id": "h5", "type": "節日起源", "title": "七夕 (乞巧節)", "icon": "💖", "era": "漢朝", "year": -150, "location": "河南南陽", "coords": [32.99, 112.52], "regions": ["河南"], "content": "牛郎織女每年七月初七靠喜鵲搭橋相會。民間女子在此日乞求女紅手藝進步，稱為「乞巧節」。", "evidence": "南陽出土大量漢代牛郎織女畫像石，被學界廣泛認為是故事發源地之一。", "link": "https://zh.wikipedia.org/zh-tw/%E4%B8%83%E5%A4%95" },
  { "id": "h6", "type": "節日起源", "title": "中秋節 (月餅起義)", "icon": "🥮", "era": "元末明初", "year": 1368, "location": "江蘇南京", "coords": [32.00, 118.80], "regions": ["江蘇", "安徽", "台灣"], "content": "相傳軍師劉伯溫想出將寫有「八月十五夜起義」的紙條藏入月餅中，成功傳遞消息，後成中秋吃月餅習俗。", "evidence": "中秋節源於秋季祭月，月餅起義是明清時期民間為月餅賦予的傳奇色彩故事。", "link": "https://zh.wikipedia.org/zh-tw/%E4%B8%AD%E7%A7%8B%E8%8A%82" },
  { "id": "h7", "type": "節日起源", "title": "重陽節 (桓景避災)", "icon": "🏔️", "era": "東漢", "year": 150, "location": "河南汝南", "coords": [33.00, 114.00], "regions": ["河南"], "content": "傳說汝南人桓景跟隨仙人費長房學道，九月初九帶鄉親登高、佩茱萸、飲菊花酒，成功避開瘟禍。", "evidence": "《續齊諧記》。重陽節有登高、敬老、佩茱萸的習俗。", "link": "https://zh.wikipedia.org/zh-tw/%E9%87%8D%E9%98%B3%E8%8A%82" },
  { "id": "h8", "type": "節日起源", "title": "秋夕 (韓國感恩節)", "icon": "🍂", "era": "新羅時期", "year": 30, "location": "韓國", "coords": [36.0, 128.0], "regions": ["韓國"], "content": "源自新羅早期的織布比賽「嘉俳」，如今是韓國人回鄉祭祖、掃墓，並吃「松餅」感謝秋收的重大節日。", "evidence": "《三國史記》。秋夕在韓國是與春節並列的最大傳統節日。", "link": "https://zh.wikipedia.org/wiki/%E7%A7%8B%E5%A4%95" },

  // --- 成語故事類 ---
  { "id": "i1", "type": "成語故事", "title": "完璧歸趙", "icon": "💎", "era": "戰國時期", "year": -283, "location": "河北邯鄲", "coords": [36.6, 114.5], "regions": ["河北", "陝西"], "content": "秦昭王想用城池換取和氏璧，藺相如奉命帶璧出使，憑藉機智勇敢，最終將和氏璧完好歸還趙國。", "evidence": "《史記·廉頗藺相如列傳》。比喻把原物完好地歸還本人。", "link": "https://zh.wiktionary.org/zh-hant/%E5%AE%8C%E7%92%A7%E6%AD%B8%E8%B6%99" },
  { "id": "i2", "type": "成語故事", "title": "破釜沉舟", "icon": "💥", "era": "秦末漢初", "year": -207, "location": "河北巨鹿", "coords": [37.22, 115.03], "regions": ["河北"], "content": "項羽渡河救援巨鹿後，下令砸碎鍋具、鑿沉船隻，只帶三天乾糧，以示必死決心，最終大破秦軍。", "evidence": "《史記·項羽本紀》。比喻下定必死的決心，不留退路。", "link": "https://zh.wikipedia.org/zh-tw/%E7%A0%B4%E9%87%9C%E6%B2%89%E8%88%9F" },
  { "id": "i3", "type": "成語故事", "title": "草木皆兵", "icon": "🍃", "era": "東晉", "year": 383, "location": "安徽壽縣 (淝水)", "coords": [32.58, 116.78], "regions": ["安徽"], "content": "淝水之戰中，前秦皇帝苻堅見東晉軍隊陣容嚴整，把八公山上的草木都當成了晉軍，心中十分恐懼。", "evidence": "《晉書·苻堅載記》。形容人在驚慌時疑神疑鬼。", "link": "https://zh.wiktionary.org/zh-hant/%E8%8D%89%E6%9C%A8%E7%9A%86%E5%85%B5" },
  { "id": "i4", "type": "成語故事", "title": "揠苗助長", "icon": "🌱", "era": "春秋戰國", "year": -400, "location": "河南商丘 (宋國)", "coords": [34.4, 115.6], "regions": ["河南"], "content": "宋國有個人嫌禾苗長得太慢，就把禾苗一棵棵往上拔高，結果禾苗反而全都枯死了。", "evidence": "《孟子·公孫丑上》。比喻違反規律急於求成，反而把事情弄糟。", "link": "https://zh.wiktionary.org/zh-hant/%E6%8F%A0%E8%8B%97%E5%8A%A9%E9%95%B7" },
  { "id": "i5", "type": "成語故事", "title": "守株待兔", "icon": "🐇", "era": "春秋戰國", "year": -350, "location": "河南商丘 (宋國)", "coords": [34.3, 115.7], "regions": ["河南"], "content": "宋國農夫偶然撿到一隻撞死在樹樁上的兔子，從此放下農具，天天守在樹樁旁希望能再撿到兔子。", "evidence": "《韓非子·五蠹》。比喻拘泥守成，不知變通，或妄想不勞而獲。", "link": "https://zh.wiktionary.org/zh-hant/%E5%AE%88%E6%A0%AA%E5%BE%85%E5%85%94" },
  { "id": "i6", "type": "成語故事", "title": "刻舟求劍", "icon": "🗡️", "era": "戰國時期", "year": -300, "location": "湖北荊州 (楚國)", "coords": [30.3, 112.2], "regions": ["湖北"], "content": "楚國人渡江時劍掉入水中，他在船身刻下記號，等船靠岸後才從記號處下水找劍。", "evidence": "《呂氏春秋·察今》。比喻辦事刻板，不知道因時制宜。", "link": "https://zh.wiktionary.org/zh-hant/%E5%88%BB%E8%88%9F%E6%B1%82%E5%8A%8D" },
  { "id": "i7", "type": "成語故事", "title": "掩耳盜鈴", "icon": "🔔", "era": "春秋時期", "year": -450, "location": "山西太原 (晉國)", "coords": [37.8, 112.5], "regions": ["山西"], "content": "有人偷了一口大鐘，想把它敲碎帶走，怕鐘聲引來別人，就捂住自己的耳朵去砸。", "evidence": "《呂氏春秋·自知》。比喻自欺欺人。", "link": "https://zh.wiktionary.org/zh-hant/%E6%8E%A9%E8%80%B3%E7%9B%9C%E9%88%B4" },
  { "id": "i8", "type": "成語故事", "title": "指鹿為馬", "icon": "🦌", "era": "秦朝", "year": -207, "location": "陝西咸陽", "coords": [34.3, 108.7], "regions": ["陝西"], "content": "權臣趙高為了測試群臣是否順從他，牽了一隻鹿獻給秦二世，卻硬說是一匹馬。", "evidence": "《史記·秦始皇本紀》。比喻顛倒是非，混淆黑白。", "link": "https://zh.wiktionary.org/zh-hant/%E6%8C%87%E9%B9%BF%E7%82%BA%E9%A6%AC" },
  { "id": "i9", "type": "成語故事", "title": "臥薪嘗膽", "icon": "🪵", "era": "春秋時期", "year": -494, "location": "浙江紹興 (越國)", "coords": [30.0, 120.5], "regions": ["浙江", "江蘇"], "content": "越王勾踐戰敗後，睡在柴草上，每天嚐一口苦膽，不忘復國之恥，最終消滅了吳國。", "evidence": "《史記·越王勾踐世家》。比喻刻苦自勵，發憤圖強。", "link": "https://zh.wiktionary.org/zh-hant/%E8%87%A5%E8%96%AA%E5%98%97%E8%86%BD" },
  { "id": "i10", "type": "成語故事", "title": "三顧茅廬", "icon": "🛖", "era": "東漢末年", "year": 207, "location": "湖北襄陽 (隆中)", "coords": [32.0, 112.1], "regions": ["湖北"], "content": "劉備為了求得諸葛亮出山輔佐，三次親自到南陽隆中的草廬去拜訪他。", "evidence": "《三國志·諸葛亮傳》。比喻誠心誠意地邀請人家。", "link": "https://zh.wiktionary.org/zh-hant/%E4%B8%89%E9%A1%A7%E8%8C%85%E5%BB%AC" },
  { "id": "i11", "type": "成語故事", "title": "聞雞起舞", "icon": "🐓", "era": "東晉", "year": 313, "location": "河北保定", "coords": [38.8, 115.5], "regions": ["河北"], "content": "祖逖與好友劉琨為了報效國家，半夜聽到雞叫聲就起床拔劍練武。", "evidence": "《晉書·祖逖傳》。比喻有志之士奮發圖強。", "link": "https://zh.wiktionary.org/zh-hant/%E8%81%9E%E9%9B%9E%E8%B5%B7%E8%88%9E" },
  { "id": "i12", "type": "成語故事", "title": "望梅止渴", "icon": "🍒", "era": "東漢末年", "year": 198, "location": "河南許昌", "coords": [34.0, 113.8], "regions": ["河南", "安徽"], "content": "曹操率軍行軍途中缺水，便騙士兵前面有一大片梅林，士兵聽了流出口水，便暫時解了渴。", "evidence": "《世說新語·假譎》。比喻用空想來安慰自己。", "link": "https://zh.wiktionary.org/zh-hant/%E6%9C%9B%E6%A2%85%E6%AD%A2%E6%B8%B4" },
  { "id": "i13", "type": "成語故事", "title": "狐假虎威", "icon": "🦊", "era": "戰國時期", "year": -330, "location": "湖北一帶 (楚國)", "coords": [30.5, 114.3], "regions": ["湖北", "湖南"], "content": "老虎抓住狐狸，狐狸謊稱自己是百獸之王，讓老虎跟在後面走，野獸看到老虎都嚇跑了，老虎以為是怕狐狸。", "evidence": "《戰國策·楚策一》。比喻藉著有權勢者的威風來欺壓別人。", "link": "https://zh.wiktionary.org/zh-hant/%E7%8B%90%E5%81%87%E8%99%8E%E5%A8%81" },
  { "id": "i14", "type": "成語故事", "title": "井底之蛙", "icon": "🐸", "era": "戰國時期", "year": -300, "location": "黃河流域", "coords": [34.8, 114.0], "regions": ["山東", "河南"], "content": "井裡的青蛙以為天只有井口那麼大，對來自東海的海鱉誇耀生活，卻不知外面的世界有多寬廣。", "evidence": "《莊子·秋水》。比喻見識短淺的人。", "link": "https://zh.wiktionary.org/zh-hant/%E4%BA%95%E5%BA%95%E4%B9%8B%E8%9B%99" }
];